name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      docker_image: ${{ steps.build.outputs.docker_image }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Build
        id: build
        run: ./ci/build.sh
