name: build

on:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      docker_image: ${{ steps.build.outputs.docker_image }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Build
        id: build
        run: ./ci/build.sh
  deploy-dev:
    if: ${{ github.event_name == 'push' }}
    needs: [build]
    uses: ./.github/workflows/deploy-job.yml
    with:
      env: dev
      image: ${{ steps.build.outputs.docker_image }}
  deploy-stage:
    if: ${{ github.event_name == 'release' && github.event.release.prerelease && ! github.event.release.draft }}
    needs: [build]
    uses: ./.github/workflows/deploy-job.yml
    with:
      env: stage
      image: ${{ steps.build.outputs.docker_image }}
  deploy-prod:
    if: ${{ github.event_name == 'release' && ! github.event.release.prerelease && ! github.event.release.draft }}
    needs: [build]
    uses: ./.github/workflows/deploy-job.yml
    with:
      env: prod
      image: ${{ steps.build.outputs.docker_image }}
