name: Deploy

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  push:
    branches: [master]
  release:
    types: [published]

env:
  ENVIRONMENT: '$(whoami)'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev: &deploy
    name: Deploy to develop
    runs-on: ubuntu-latest
    steps:
      - name: print
        env:
          GITHUB_CONTEXT: '${{ toJson(github) }}'
        run: |
          echo Environment "$ENVIRONMENT"
          echo "$GITHUB_CONTEXT"
  deploy-stage:
    <<: *deploy
    name: Deploy to stage
  deploy-prod:
    <<: *deploy
    name: Deploy to prod
