# This will become a bit simpler when this issue is completed:
# https://github.com/actions/runner/issues/1182

name: Deploy

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  push:
    branches: [master]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev:
    name: Deploy to develop
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/deploy-job.yml
    with:
      env: dev
  stage:
    name: Deploy to stage
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'release' && github.event.release.prerelease && ! github.event.release.draft }}
    uses: ./.github/workflows/deploy-job.yml
    with:
      env: stage
  prod:
    name: Deploy to prod
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'release' && ! github.event.release.prerelease && ! github.event.release.draft }}
    uses: ./.github/workflows/deploy-job.yml
    with:
      env: prod
