# This will become a bit simpler when this issue is completed:
# https://github.com/actions/runner/issues/1182

name: Deploy

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  push:
    branches: [master]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev:
    name: Deploy to develop
    environment: dev
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: print
        env:
          ENV: dev
          GITHUB_CONTEXT: '${{ toJson(github) }}'
        run: ./ci/deploy.sh
  deploy-stage:
    name: Deploy to stage
    environment: stage
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'release' && github.event.release.prerelease && ! github.event.release.draft }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: print
        env:
          ENV: stage
          GITHUB_CONTEXT: '${{ toJson(github) }}'
        run: ./ci/deploy.sh
  deploy-prod:
    name: Deploy to prod
    environment: prod
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'release' && ! github.event.release.prerelease && ! github.event.release.draft }}
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: print
        env:
          ENV: prod
          GITHUB_CONTEXT: '${{ toJson(github) }}'
        run: ./ci/deploy.sh
