name: Deploy

on:
  push:
    branches: [master]
  release:
    types: [published]

env:
  ENVIRONMENT: '$(whoami)'

defaults:
  runs-on: ubuntu-latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-dev:
    name: Deploy to develop
    steps: &steps
      - name: print
        env:
          GITHUB_CONTEXT: '${{ toJson(github) }}'
        run: echo "$GITHUB_CONTEXT" "$ENVIRONMENT"
  deploy-stage:
    name: Deploy to stage
    steps: *steps
  deploy-prod:
    name: Deploy to stage
    steps: *steps
